### ISSUE TITLE
Error map001

### ISSUE THREAD

**Issue by Blunnyn** [insthync/unity-simple-asset-bundle-client#1]
I have a problem loading map001. 
My map file is called Mapa001 (with an A at the end) but when playing the game it asks for the Map001 file (as it comes by default.

<img width="878" alt="Captura de Pantalla 2021-10-18 a la(s) 22 33 30" src="https://user-images.githubusercontent.com/45702662/137829195-2af052dd-add3-47aa-adaa-748d0f680bf7.png">
t)
<img width="1203" alt="Captura de Pantalla 2021-10-18 a la(s) 22 34 17" src="https://user-images.githubusercontent.com/45702662/137829250-f786cee2-4267-49a4-a83b-7b6dc9ad5209.png">

and so it is in the database
<img width="546" alt="Captura de Pantalla 2021-10-18 a la(s) 22 35 20" src="https://user-images.githubusercontent.com/45702662/137829335-a70a0298-1b0c-4de7-89ad-483250675205.png">

**Comment by insthync** [comment]
Try drag map scene to map data to refresh scene name data for example:

Drag `mapa001(scene)` to `Mapa001(MapInfo)` -> `Scene`

**Comment by Blunnyn** [comment]
I did it, but it didn't work.

I had to change the name to Map001 (without the A) and it worked
