### ISSUE TITLE
Checker

### ISSUE THREAD

**Issue by AsheshPlays** [insthync/unity-simple-asset-bundle-client#2]
Hi! Im currently using this with your kit. Does this have version checker for APK if apk has been updated on playstore? And can this also show patch notes or change log?

**Comment by insthync** [comment]
It is a different thing, You actually should upload a file with the version number somewhere and use Unity's WebRequest class to read the file.

You may look a this example https://github.com/insthync/simple-version-checker

**Comment by AsheshPlays** [comment]
will this work with pastebin?

**Comment by insthync** [comment]
I don't know that ,Pastebin has a api to get just content or not.

**Comment by AsheshPlays** [comment]
@insthync Thanks for the tip tho.. Im sorry I have been asking and have been quite a hassle for some time now. But i really appreciate your doings.
